### ISSUE TITLE
can not find mod_spatialite in project

### ISSUE THREAD

**Issue by Masoud-kamali** [chrkaatz/node-spatialite#4]
Hi, at first thank you for this example. I want to load mod_spatialite extension to my db, but it can not find mod_spatialite in project.
also, I add mod_spatialite.dll file to my project. but it does not work.
Thanks.

**Comment by chrkaatz** [comment]
I will have a look into this

**Comment by chrkaatz** [comment]
The latest docker images work again - @Masoud-kamali you can verify it my checking out this repo and run the example.

```bash
$ cd example
$ docker build -t node-spatialite-example .
$ docker run -it --rm node-spatialite-example
```
